// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

import { exportCSSFromProps } from "../runtime/export/exportCSSFromProps";

export function createProgressBarSchema() {
  return {
    description: "",
    editor: {
      defaultOpenGroups: {
        content: ["Content"],
        layout: ["Size"],
        selectors: [],
        styling: ["Typography"],
        visibility: [],
      },
      roleGroupOrder: {
        content: ["Content"],
        layout: ["Size"],
        selectors: ["Selectors"],
        styling: ["Typography", "Surface", "Border"],
        visibility: ["Visibility"],
      },
      roleOrder: ["content", "styling", "layout", "visibility", "selectors"],
    },
    exportCSS: (progressBar = null, progressBarSchema = null) => {
      return "";
    },
    exportHTML: (progressBar, progressBarSchema, pageSchema, indentation) => {
      return "";
    },
    isAllowingChildComponents: false,
    label: "ProgressBar",
    plan: "Pro",
    props: {
      value: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: 50,
        label: "Value",
        role: "content",
        roleGroup: "Content",
        schemaType: "number",
        type: "number",
      },
      color: {
        cssProperty: "color",
        cssVariableName: "--progress-bar-color",
        defaultValue: "var(--pc-semantic-text-inverse)",
        label: "Color",
        role: "styling",
        roleGroup: "Typography",
        schemaType: "string",
        type: "color",
      },
      fontSize: {
        cssProperty: "font-size",
        cssVariableName: "--progress-bar-font-size",
        defaultValue: "1rem",
        label: "Font size",
        role: "styling",
        roleGroup: "Typography",
        schemaType: "string",
        type: "text",
      },
      backgroundColor: {
        cssProperty: "background-color",
        cssVariableName: "--progress-bar-background-color",
        defaultValue: "var(--pc-foundation-color-slate-300)",
        label: "Background color",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "color",
      },
      background: {
        cssProperty: "background",
        cssVariableName: "--progress-bar-background",
        defaultValue: "none",
        label: "Background",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      backgroundColorProgress: {
        cssProperty: "background-color",
        cssVariableName: "--progress-bar-background-color-progress",
        defaultValue: "var(--pc-semantic-status-primary)",
        label: "Background color - Progress",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "color",
      },
      backgroundProgress: {
        cssProperty: "background",
        cssVariableName: "--progress-bar-background-progress",
        defaultValue: "none",
        label: "Background - Progress",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      borderWidth: {
        cssProperty: "border-width",
        cssVariableName: "--progress-bar-border-width",
        defaultValue: "1px",
        label: "Border width",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      borderColor: {
        cssProperty: "border-color",
        cssVariableName: "--progress-bar-border-color",
        defaultValue: "var(--pc-semantic-status-primary)",
        label: "Border color",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "color",
      },
      borderRadius: {
        cssProperty: "border-radius",
        cssVariableName: "--progress-bar-border-radius",
        defaultValue: "8px",
        label: "Border radius",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      borderWidthProgress: {
        cssProperty: "border-width",
        cssVariableName: "--progress-bar-border-width-progress",
        defaultValue: "1px",
        label: "Border width - Progress",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      borderColorProgress: {
        cssProperty: "border-color",
        cssVariableName: "--progress-bar-border-color-progress",
        defaultValue: "var(--pc-semantic-status-primary)",
        label: "Border color - Progress",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "color",
      },
      borderRadiusProgress: {
        cssProperty: "border-radius",
        cssVariableName: "--progress-bar-border-radius-progress",
        defaultValue: "0px",
        label: "Border radius - Progress",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      width: {
        cssProperty: "width",
        cssVariableName: "--progress-bar-width",
        defaultValue: "100%",
        label: "Width",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      height: {
        cssProperty: "height",
        cssVariableName: "--progress-bar-height",
        defaultValue: "25px",
        label: "Height",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      isVisible: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: true,
        isExpressionUnsupported: true,
        label: "Is visible",
        role: "visibility",
        roleGroup: "Visibility",
        schemaType: "boolean",
        type: "switch",
      },
      selectors: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: [],
        label: "Selectors",
        role: "selectors",
        roleGroup: "Selectors",
        schemaType: "array",
        type: "selectors",
      },
    },
    slots: {},
  };
}
