// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

import { exportCSSFromProps } from "../runtime/export/exportCSSFromProps";

export function createElementSchema() {
  return {
    defaultProps: {
      border: "1px solid #e5e7eb",
      padding: "1rem",
    },
    defaultSlots: {
      body: [],
    },
    description: "A useful component if you cannot do what you want with other existing ones.",
    editor: {
      defaultOpenGroups: {
        content: [],
        selectors: [],
        styling: [],
        visibility: [],
      },
      roleGroupOrder: {
        content: ["Element"],
        selectors: ["Selectors"],
        styling: ["Element"],
        visibility: ["Visibility"],
      },
      roleOrder: ["content", "styling", "visibility", "selectors"],
    },
    exportCSS: (element = null, elementSchema = null) => {
      if (element && elementSchema) {
        const props = exportCSSFromProps(element, elementSchema);

        if (props.length > 0) {
          return `
      .${element.id} {
${props.map((prop) => "        " + prop).join("\n")}
      }
`;
        } else {
          return "";
        }
      } else {
        return `
      .element {
        
      }
`;
      }
    },
    exportHTML: (element, elementSchema, pageSchema, indentation) => {
      const voidElements = ["area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"];

      const elementElement = element?.props?.element || "div";

      const isVoidElement = typeof elementElement === "string" && voidElements.includes(elementElement);

      const href = typeof element?.props?.href === "string" ? element.props.href.trim() : "";
      const alt = typeof element?.props?.alt === "string" ? element.props.alt.trim() : "";
      const src = typeof element?.props?.src === "string" ? element.props.src.trim() : "";
      const text = typeof element?.props?.text === "string" || typeof element?.props?.text === "number" ? element.props.text : "";

      if (typeof element?.props?.isVisible === "boolean" && !element.props.isVisible) {
        return "";
      }

      if (isVoidElement) {
        return `${indentation}<${elementElement}${alt ? ` alt="${alt}"` : ""} class="element ${element?.id}"${src ? ` src="${src}"` : ""} />`;
      }

      return `${indentation}<${elementElement} class="element ${element?.id}" data-pc-id="${element?.id || ""}"${href ? ` href="${href}"` : ""}>${text}
${element?.slots?.body || ""}${(element?.slots?.body || "").trim() === "" ? "\n" : ""}${indentation}</${elementElement}>`;
    },
    isAllowingChildComponents: true,
    label: "Element",
    plan: "Pro Gold",
    props: {
      element: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "div",
        label: "Element",
        role: "styling",
        roleGroup: "Element",
        schemaType: "string",
        type: "text",
      },
      text: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "",
        label: "Text",
        role: "content",
        roleGroup: "Element",
        schemaType: "string",
        type: "textarea",
      },
      href: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "",
        label: "Href",
        role: "content",
        roleGroup: "Element",
        schemaType: "string",
        type: "text",
      },
      src: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "",
        label: "Src",
        role: "content",
        roleGroup: "Element",
        schemaType: "string",
        type: "text",
      },
      alt: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "",
        label: "Alt",
        role: "content",
        roleGroup: "Element",
        schemaType: "string",
        type: "text",
      },
      alignContent: {
        cssProperty: "align-content",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Align content",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      alignItems: {
        cssProperty: "align-items",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Align items",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      alignSelf: {
        cssProperty: "align-self",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Align self",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animation: {
        cssProperty: "animation",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animationDelay: {
        cssProperty: "animation-delay",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation delay",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animationDirection: {
        cssProperty: "animation-direction",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation direction",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animationDuration: {
        cssProperty: "animation-duration",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation duration",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animationFillMode: {
        cssProperty: "animation-fill-mode",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation fill mode",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animationIterationCount: {
        cssProperty: "animation-iteration-count",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation iteration count",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animationName: {
        cssProperty: "animation-name",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation name",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animationPlayState: {
        cssProperty: "animation-play-state",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation play state",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      animationTimingFunction: {
        cssProperty: "animation-timing-function",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Animation timing function",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backfaceVisibility: {
        cssProperty: "backface-visibility",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Backface visibility",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      background: {
        cssProperty: "background",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backgroundAttachment: {
        cssProperty: "background-attachment",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background attachment",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backgroundClip: {
        cssProperty: "background-clip",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background clip",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backgroundColor: {
        cssProperty: "background-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backgroundImage: {
        cssProperty: "background-image",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background image",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backgroundOrigin: {
        cssProperty: "background-origin",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background origin",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backgroundPosition: {
        cssProperty: "background-position",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background position",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backgroundRepeat: {
        cssProperty: "background-repeat",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background repeat",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      backgroundSize: {
        cssProperty: "background-size",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Background size",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      border: {
        cssProperty: "border",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderBottom: {
        cssProperty: "border-bottom",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border bottom",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderBottomColor: {
        cssProperty: "border-bottom-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border bottom color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderBottomLeftRadius: {
        cssProperty: "border-bottom-left-radius",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border bottom left radius",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderBottomRightRadius: {
        cssProperty: "border-bottom-right-radius",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border bottom right radius",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderBottomStyle: {
        cssProperty: "border-bottom-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border bottom style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderBottomWidth: {
        cssProperty: "border-bottom-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border bottom width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderCollapse: {
        cssProperty: "border-collapse",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border collapse",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderColor: {
        cssProperty: "border-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderImage: {
        cssProperty: "border-image",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border image",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderImageOutset: {
        cssProperty: "border-image-outset",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border image outset",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderImageRepeat: {
        cssProperty: "border-image-repeat",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border image repeat",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderImageSlice: {
        cssProperty: "border-image-slice",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border image slice",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderImageSource: {
        cssProperty: "border-image-source",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border image source",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderImageWidth: {
        cssProperty: "border-image-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border image width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderLeft: {
        cssProperty: "border-left",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border left",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderLeftColor: {
        cssProperty: "border-left-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border left color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderLeftStyle: {
        cssProperty: "border-left-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border left style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderLeftWidth: {
        cssProperty: "border-left-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border left width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderRadius: {
        cssProperty: "border-radius",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border radius",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderRight: {
        cssProperty: "border-right",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border right",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderRightColor: {
        cssProperty: "border-right-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border right color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderRightStyle: {
        cssProperty: "border-right-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border right style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderRightWidth: {
        cssProperty: "border-right-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border right width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderSpacing: {
        cssProperty: "border-spacing",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border spacing",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderStyle: {
        cssProperty: "border-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderTop: {
        cssProperty: "border-top",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border top",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderTopColor: {
        cssProperty: "border-top-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border top color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderTopLeftRadius: {
        cssProperty: "border-top-left-radius",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border top left radius",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderTopRightRadius: {
        cssProperty: "border-top-right-radius",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border top right radius",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderTopStyle: {
        cssProperty: "border-top-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border top style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderTopWidth: {
        cssProperty: "border-top-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border top width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      borderWidth: {
        cssProperty: "border-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Border width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      bottom: {
        cssProperty: "bottom",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Bottom",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      boxShadow: {
        cssProperty: "box-shadow",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Box shadow",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      boxSizing: {
        cssProperty: "box-sizing",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Box sizing",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      captionSide: {
        cssProperty: "caption-side",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Caption side",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      clear: {
        cssProperty: "clear",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Clear",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      clip: {
        cssProperty: "clip",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Clip",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      color: {
        cssProperty: "color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnCount: {
        cssProperty: "column-count",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column count",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnFill: {
        cssProperty: "column-fill",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column fill",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnGap: {
        cssProperty: "column-gap",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column gap",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnRule: {
        cssProperty: "column-rule",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column rule",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnRuleColor: {
        cssProperty: "column-rule-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column rule color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnRuleStyle: {
        cssProperty: "column-rule-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column rule style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnRuleWidth: {
        cssProperty: "column-rule-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column rule width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnSpan: {
        cssProperty: "column-span",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column span",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columnWidth: {
        cssProperty: "column-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Column width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      columns: {
        cssProperty: "columns",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Columns",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      content: {
        cssProperty: "content",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Content",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      counterIncrement: {
        cssProperty: "counter-increment",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Counter increment",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      counterReset: {
        cssProperty: "counter-reset",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Counter reset",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      cursor: {
        cssProperty: "cursor",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Cursor",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      direction: {
        cssProperty: "direction",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Direction",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      display: {
        cssProperty: "display",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Display",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      emptyCells: {
        cssProperty: "empty-cells",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Empty cells",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      flex: {
        cssProperty: "flex",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Flex",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      flexBasis: {
        cssProperty: "flex-basis",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Flex basis",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      flexDirection: {
        cssProperty: "flex-direction",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Flex direction",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      flexFlow: {
        cssProperty: "flex-flow",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Flex flow",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      flexGrow: {
        cssProperty: "flex-grow",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Flex grow",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      flexShrink: {
        cssProperty: "flex-shrink",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Flex shrink",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      flexWrap: {
        cssProperty: "flex-wrap",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Flex wrap",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      float: {
        cssProperty: "float",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Float",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      font: {
        cssProperty: "font",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Font",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      fontFamily: {
        cssProperty: "font-family",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Font family",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      fontSize: {
        cssProperty: "font-size",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Font size",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      fontSizeAdjust: {
        cssProperty: "font-size-adjust",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Font size adjust",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      fontStretch: {
        cssProperty: "font-stretch",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Font stretch",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      fontStyle: {
        cssProperty: "font-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Font style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      fontVariant: {
        cssProperty: "font-variant",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Font variant",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      fontWeight: {
        cssProperty: "font-weight",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Font weight",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      height: {
        cssProperty: "height",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Height",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      justifyContent: {
        cssProperty: "justify-content",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Justify content",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      left: {
        cssProperty: "left",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Left",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      letterSpacing: {
        cssProperty: "letter-spacing",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Letter spacing",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      lineHeight: {
        cssProperty: "line-height",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Line height",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      listStyle: {
        cssProperty: "list-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "List style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      listStyleImage: {
        cssProperty: "list-style-image",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "List style image",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      listStylePosition: {
        cssProperty: "list-style-position",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "List style position",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      listStyleType: {
        cssProperty: "list-style-type",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "List style type",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      margin: {
        cssProperty: "margin",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Margin",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      marginBottom: {
        cssProperty: "margin-bottom",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Margin bottom",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      marginLeft: {
        cssProperty: "margin-left",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Margin left",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      marginRight: {
        cssProperty: "margin-right",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Margin right",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      marginTop: {
        cssProperty: "margin-top",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Margin top",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      maxHeight: {
        cssProperty: "max-height",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Max height",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      maxWidth: {
        cssProperty: "max-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Max width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      minHeight: {
        cssProperty: "min-height",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Min height",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      minWidth: {
        cssProperty: "min-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Min width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      opacity: {
        cssProperty: "opacity",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Opacity",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      order: {
        cssProperty: "order",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Order",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      outline: {
        cssProperty: "outline",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Outline",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      outlineColor: {
        cssProperty: "outline-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Outline color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      outlineOffset: {
        cssProperty: "outline-offset",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Outline offset",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      outlineStyle: {
        cssProperty: "outline-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Outline style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      outlineWidth: {
        cssProperty: "outline-width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Outline width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      overflow: {
        cssProperty: "overflow",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Overflow",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      overflowX: {
        cssProperty: "overflow-x",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Overflow x",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      overflowY: {
        cssProperty: "overflow-y",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Overflow y",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      padding: {
        cssProperty: "padding",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Padding",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      paddingBottom: {
        cssProperty: "padding-bottom",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Padding bottom",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      paddingLeft: {
        cssProperty: "padding-left",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Padding left",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      paddingRight: {
        cssProperty: "padding-right",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Padding right",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      paddingTop: {
        cssProperty: "padding-top",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Padding top",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      pageBreakAfter: {
        cssProperty: "page-break-after",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Page break after",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      pageBreakBefore: {
        cssProperty: "page-break-before",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Page break before",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      pageBreakInside: {
        cssProperty: "page-break-inside",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Page break inside",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      perspective: {
        cssProperty: "perspective",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Perspective",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      perspectiveOrigin: {
        cssProperty: "perspective-origin",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Perspective origin",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      position: {
        cssProperty: "position",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Position",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      quotes: {
        cssProperty: "quotes",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Quotes",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      resize: {
        cssProperty: "resize",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Resize",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      right: {
        cssProperty: "right",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Right",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      tabSize: {
        cssProperty: "tab-size",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Tab size",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      tableLayout: {
        cssProperty: "table-layout",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Table layout",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textAlign: {
        cssProperty: "text-align",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text align",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textAlignLast: {
        cssProperty: "text-align-last",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text align last",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textDecoration: {
        cssProperty: "text-decoration",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text decoration",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textDecorationColor: {
        cssProperty: "text-decoration-color",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text decoration color",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textDecorationLine: {
        cssProperty: "text-decoration-line",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text decoration line",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textDecorationStyle: {
        cssProperty: "text-decoration-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text decoration style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textIndent: {
        cssProperty: "text-indent",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text indent",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textJustify: {
        cssProperty: "text-justify",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text justify",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textOverflow: {
        cssProperty: "text-overflow",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text overflow",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textShadow: {
        cssProperty: "text-shadow",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text shadow",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      textTransform: {
        cssProperty: "text-transform",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Text transform",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      top: {
        cssProperty: "top",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Top",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      transform: {
        cssProperty: "transform",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Transform",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      transformOrigin: {
        cssProperty: "transform-origin",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Transform origin",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      transformStyle: {
        cssProperty: "transform-style",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Transform style",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      transition: {
        cssProperty: "transition",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Transition",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      transitionDelay: {
        cssProperty: "transition-delay",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Transition delay",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      transitionDuration: {
        cssProperty: "transition-duration",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Transition duration",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      transitionProperty: {
        cssProperty: "transition-property",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Transition property",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      transitionTimingFunction: {
        cssProperty: "transition-timing-function",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Transition timing function",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      verticalAlign: {
        cssProperty: "vertical-align",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Vertical align",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      visibility: {
        cssProperty: "visibility",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Visibility",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      whiteSpace: {
        cssProperty: "white-space",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "White space",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      width: {
        cssProperty: "width",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Width",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      wordBreak: {
        cssProperty: "word-break",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Word break",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      wordSpacing: {
        cssProperty: "word-spacing",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Word spacing",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      wordWrap: {
        cssProperty: "word-wrap",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Word wrap",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      zIndex: {
        cssProperty: "z-index",
        cssPropertyOverride: true,
        cssVariableName: null,
        defaultValue: "",
        label: "Z index",
        role: "styling",
        roleGroup: "Styling",
        schemaType: "string",
        type: "text",
      },
      isVisible: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: true,
        label: "Is visible",
        role: "visibility",
        roleGroup: "Visibility",
        schemaType: "boolean",
        type: "switch",
      },
      selectors: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: [],
        label: "Selectors",
        role: "selectors",
        roleGroup: "Selectors",
        schemaType: "array",
        type: "selectors",
      },
    },
    slots: {
      body: {
        allowedChildComponents: ["Alert", "Badge", "Button", "Card", "Checkbox", "Dialog", "Divider", "Element", "Footer", "Form", "Grid", "Heading", "Image", "Input", "Label", "Link", "List", "ListItem", "Map", "MenuBar", "RadioGroup", "RichText", "Section", "Select", "SideBar", "Spacer", "Spinner", "Switch", "Table", "TableData", "TableHeader", "TableRow", "Text", "TextArea"],
      },
    },
  };
}
