// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

export function getExpressionSchema() {
  return {
    abs: {
      description: "Returns the absolute value of a number.",
      group: "Math",
      label: "Abs",
      parameters: {
        value: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    acos: {
      description: "Returns the inverse cosine of a number in radians.",
      group: "Math",
      label: "Acos",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    acosh: {
      description: "Returns the inverse hyperbolic cosine of a number.",
      group: "Math",
      label: "Acosh",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    add: {
      description: "Returns the sum of the addition.\nEach value supplied should preferably be a number or an array of numbers. But other types are supported and will be deeply reduced and coerced to numbers.",
      group: "Math",
      label: "Add",
      parameters: {
        values: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<number>", "number"],
          label: "Values",
          type: "array<number>",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    all: {
      group: "Collections",
      label: "All",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
      },
      plan: "Pro",
      returnType: "boolean",
    },
    and: {
      group: "Logic",
      label: "And",
      parameters: {
        values: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<boolean>", "boolean"],
          label: "Values",
          type: "array<boolean>",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    any: {
      group: "Collections",
      label: "Any",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
      },
      plan: "Pro",
      returnType: "boolean",
    },
    asin: {
      description: "Returns the inverse sine of a number in radians.",
      group: "Math",
      label: "Asin",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    asinh: {
      description: "Returns the inverse hyperbolic sine of a number.",
      group: "Math",
      label: "Asinh",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    atan: {
      description: "Returns the inverse tangent of a number in radians.",
      group: "Math",
      label: "Atan",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    atan2: {
      description: "Returns the radian-based angle in the plane between the positive X-axis and the ray from (0, 0) to the point (x, y).",
      group: "Math",
      label: "Atan2",
      parameters: {
        y: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    atanh: {
      description: "Returns the inverse hyperbolic tangent of a number.",
      group: "Math",
      label: "Atanh",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    average: {
      description: "Returns the average number of the supplied array, or 0 if the array is empty.\nEach array item supplied should preferably be a number or an array of numbers. But other types are supported and will be deeply reduced and coerced to numbers.",
      group: "Math",
      label: "Average",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<number>", "number"],
          label: "Array",
          type: "array<number>",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    canvasDeltaTime: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas delta time",
      labelShort: "Delta time",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    canvasFPS: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas FPS",
      labelShort: "FPS",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    canvasFrame: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas frame",
      labelShort: "Frame",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    canvasHeight: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas height",
      labelShort: "Height",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    canvasKeyDown: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas key down",
      labelShort: "Key down",
      parameters: {
        key: {
          defaultValue: "Enter",
          isExpressionAllowed: true,
          label: "Key",
          type: "string",
        },
      },
      plan: "Pro Gold",
      returnType: "boolean",
    },
    canvasMouseButton: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas mouse button",
      labelShort: "Mouse button",
      parameters: {},
      plan: "Pro Gold",
      returnType: "string",
    },
    canvasMouseDown: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas mouse down",
      labelShort: "Mouse down",
      parameters: {},
      plan: "Pro Gold",
      returnType: "boolean",
    },
    canvasMouseMoved: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas mouse moved",
      labelShort: "Mouse moved",
      parameters: {},
      plan: "Pro Gold",
      returnType: "boolean",
    },
    canvasMousePressed: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas mouse pressed",
      labelShort: "Mouse pressed",
      parameters: {},
      plan: "Pro Gold",
      returnType: "boolean",
    },
    canvasMouseReleased: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas mouse released",
      labelShort: "Mouse released",
      parameters: {},
      plan: "Pro Gold",
      returnType: "boolean",
    },
    canvasMouseWheel: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas mouse wheel",
      labelShort: "Mouse wheel",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    canvasMouseX: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas mouse X",
      labelShort: "Mouse X",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    canvasMouseY: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas mouse Y",
      labelShort: "Mouse Y",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    canvasTime: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas time",
      labelShort: "Time",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    canvasWidth: {
      componentType: "Canvas",
      group: "Canvas",
      label: "Canvas width",
      labelShort: "Width",
      parameters: {},
      plan: "Pro Gold",
      returnType: "number",
    },
    ceil: {
      description: "Returns the smallest integer greater than or equal to the given number.",
      group: "Math",
      label: "Ceil",
      parameters: {
        value: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    clamp: {
      group: "Math",
      label: "Clamp",
      parameters: {
        value: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
        min: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Min",
          type: "number",
        },
        max: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Max",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    coalesce: {
      group: "Logic",
      label: "Coalesce",
      parameters: {
        values: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Values",
          type: "array",
        },
      },
      plan: "Personal",
      returnType: "any",
    },
    concat: {
      group: "Text",
      label: "Concatenate",
      labelShort: "Concat",
      parameters: {
        values: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<string>", "string"],
          label: "Values",
          type: "array<string>",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    contains: {
      group: "Text",
      label: "Contains",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
        search: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Search",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    cos: {
      description: "Returns the cosine of a number in radians.",
      group: "Math",
      label: "Cos",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    cosh: {
      description: "Returns the hyperbolic cosine of a number.",
      group: "Math",
      label: "Cosh",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    count: {
      group: "Collections",
      label: "Count",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    dateAdd: {
      group: "Date & Time",
      label: "Date add",
      labelShort: "Add",
      parameters: {
        date: {
          defaultValue: new Date().toISOString(),
          isExpressionAllowed: true,
          label: "Date",
          type: ["number", "string"],
        },
        amount: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Amount",
          type: "number",
        },
        unit: {
          defaultValue: "days",
          isExpressionAllowed: false,
          label: "Unit",
          options: [
            { label: "Seconds", value: "seconds" },
            { label: "Minutes", value: "minutes" },
            { label: "Hours", value: "hours" },
            { label: "Days", value: "days" },
            { label: "Months", value: "months" },
            { label: "Years", value: "years" },
          ],
          type: "enum<string>",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    dateDiff: {
      group: "Date & Time",
      label: "Date difference",
      labelShort: "Difference",
      parameters: {
        start: {
          defaultValue: new Date().toISOString(),
          isExpressionAllowed: true,
          label: "Start",
          type: ["number", "string"],
        },
        end: {
          defaultValue: new Date().toISOString(),
          isExpressionAllowed: true,
          label: "End",
          type: ["number", "string"],
        },
        unit: {
          defaultValue: "days",
          isExpressionAllowed: false,
          label: "Unit",
          options: [
            { label: "Seconds", value: "seconds" },
            { label: "Minutes", value: "minutes" },
            { label: "Hours", value: "hours" },
            { label: "Days", value: "days" },
          ],
          type: "enum<string>",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    datePart: {
      group: "Date & Time",
      label: "Date part",
      labelShort: "Part",
      parameters: {
        date: {
          defaultValue: new Date().toISOString(),
          isExpressionAllowed: true,
          label: "Date",
          type: ["number", "string"],
        },
        part: {
          defaultValue: "year",
          isExpressionAllowed: false,
          label: "Part",
          options: [
            { label: "Year", value: "year" },
            { label: "Month", value: "month" },
            { label: "Day", value: "day" },
            { label: "Hour", value: "hour" },
            { label: "Minute", value: "minute" },
            { label: "Second", value: "second" },
          ],
          type: "enum<string>",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    degreesToRadians: {
      group: "Conversion",
      label: "Degrees to radians",
      parameters: {
        degrees: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Degrees",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    distinct: {
      group: "Collections",
      label: "Distinct",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
      },
      plan: "Pro",
      returnType: "array",
    },
    divide: {
      group: "Math",
      label: "Divide",
      parameters: {
        left: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Left",
          type: "number",
        },
        right: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Right",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    equals: {
      group: "Logic",
      label: "Equals",
      parameters: {
        left: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Left",
          type: "any",
        },
        right: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Right",
          type: "any",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    filter: {
      group: "Collections",
      label: "Filter",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
        condition: {
          defaultValue: true,
          isExpressionAllowed: true,
          label: "Condition",
          type: "boolean",
        },
        recursive: {
          defaultValue: false,
          isExpressionAllowed: true,
          label: "Recursive",
          type: "boolean",
        },
      },
      plan: "Pro",
      returnType: "array",
    },
    first: {
      group: "Collections",
      label: "First",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
      },
      plan: "Pro",
      returnType: "any",
    },
    floor: {
      description: "Returns the largest integer less than or equal to the given number.",
      group: "Math",
      label: "Floor",
      parameters: {
        value: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    formatDate: {
      group: "Date & Time",
      label: "Format date",
      labelShort: "Format",
      parameters: {
        date: {
          defaultValue: new Date().toISOString(),
          isExpressionAllowed: true,
          label: "Date",
          type: ["number", "string"],
        },
        locale: {
          defaultValue: "en-US",
          isExpressionAllowed: true,
          label: "Locale",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    getByKey: {
      group: "Object",
      label: "Get by key",
      parameters: {
        object: {
          defaultValue: {},
          isExpressionAllowed: true,
          label: "Object",
          type: "any",
        },
        key: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Key",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "any",
    },
    greaterThan: {
      group: "Logic",
      label: "Greater than",
      parameters: {
        left: {
          defaultValue: 2,
          isExpressionAllowed: true,
          label: "Left",
          type: "number",
        },
        right: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Right",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    greaterThanOrEqualTo: {
      group: "Logic",
      label: "Greater than or equal to",
      parameters: {
        left: {
          defaultValue: 2,
          isExpressionAllowed: true,
          label: "Left",
          type: "number",
        },
        right: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Right",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    groupBy: {
      group: "Collections",
      label: "Group by",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
        key: {
          defaultValue: "key",
          isExpressionAllowed: true,
          label: "Key",
          type: "any",
        },
      },
      plan: "Pro Gold",
      returnType: "array",
    },
    hoursToMilliseconds: {
      group: "Conversion",
      label: "Hours to milliseconds",
      parameters: {
        hours: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Hours",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    hoursToMinutes: {
      group: "Conversion",
      label: "Hours to minutes",
      parameters: {
        hours: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Hours",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    hoursToSeconds: {
      group: "Conversion",
      label: "Hours to seconds",
      parameters: {
        hours: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Hours",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    if: {
      group: "Logic",
      label: "If",
      parameters: {
        condition: {
          defaultValue: true,
          isExpressionAllowed: true,
          label: "Condition",
          type: "boolean",
        },
        then: {
          defaultValue: true,
          isExpressionAllowed: true,
          label: "Then",
          type: "any",
        },
        else: {
          defaultValue: false,
          isExpressionAllowed: true,
          label: "Else",
          type: "any",
        },
      },
      plan: "Personal",
      returnType: "any",
    },
    includes: {
      group: "Logic",
      label: "Includes",
      parameters: {
        value: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Value",
          type: "array",
        },
        search: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Search",
          type: "any",
        },
      },
      plan: "Pro",
      returnType: "boolean",
    },
    isDesktop: {
      group: "Viewport",
      label: "Is desktop",
      parameters: {},
      plan: "Personal",
      returnType: "boolean",
    },
    isEmail: {
      group: "Text",
      label: "Is e-mail",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    isLandscape: {
      group: "Viewport",
      label: "Is landscape",
      parameters: {},
      plan: "Personal",
      returnType: "boolean",
    },
    isMobile: {
      group: "Viewport",
      label: "Is mobile",
      parameters: {},
      plan: "Personal",
      returnType: "boolean",
    },
    isPlatformUserAdmin: {
      group: "Platform User",
      label: "Is platform user admin",
      labelShort: "Is admin",
      parameters: {},
      plan: "Pro",
      returnType: "boolean",
    },
    isPlatformUserAuthenticated: {
      group: "Platform User",
      label: "Is platform user authenticated",
      labelShort: "Is authenticated",
      parameters: {},
      plan: "Personal",
      returnType: "boolean",
    },
    isPlatformUserWebsiteOwner: {
      group: "Platform User",
      label: "Is platform user website owner",
      labelShort: "Is website owner",
      parameters: {},
      plan: "Personal",
      returnType: "boolean",
    },
    isPortrait: {
      group: "Viewport",
      label: "Is portrait",
      parameters: {},
      plan: "Personal",
      returnType: "boolean",
    },
    isSocketConnected: {
      group: "Socket",
      label: "Is socket connected",
      labelShort: "Is connected",
      parameters: {},
      plan: "Pro Gold",
      returnType: "boolean",
    },
    isSocketDisconnected: {
      group: "Socket",
      label: "Is socket disconnected",
      labelShort: "Is disconnected",
      parameters: {},
      plan: "Pro Gold",
      returnType: "boolean",
    },
    isSocketReconnecting: {
      group: "Socket",
      label: "Is socket reconnecting",
      labelShort: "Is reconnecting",
      parameters: {},
      plan: "Pro Gold",
      returnType: "boolean",
    },
    isTablet: {
      group: "Viewport",
      label: "Is tablet",
      parameters: {},
      plan: "Personal",
      returnType: "boolean",
    },
    isUserAuthenticated: {
      group: "User",
      label: "Is user authenticated",
      labelShort: "Is authenticated",
      parameters: {},
      plan: "Pro Gold",
      returnType: "boolean",
    },
    join: {
      group: "Text",
      label: "Join",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
        separator: {
          defaultValue: ",",
          isExpressionAllowed: true,
          label: "Separator",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    last: {
      group: "Collections",
      label: "Last",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
      },
      plan: "Pro",
      returnType: "any",
    },
    length: {
      group: "Collections",
      label: "Length",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    lessThan: {
      group: "Logic",
      label: "Less than",
      parameters: {
        left: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Left",
          type: "number",
        },
        right: {
          defaultValue: 2,
          isExpressionAllowed: true,
          label: "Right",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    lessThanOrEqualTo: {
      group: "Logic",
      label: "Less than or equal to",
      parameters: {
        left: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Left",
          type: "number",
        },
        right: {
          defaultValue: 2,
          isExpressionAllowed: true,
          label: "Right",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    literal: {
      group: "Constants",
      label: "Literal",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Value",
          type: "any",
        },
      },
      plan: "Personal",
      returnType: "any",
    },
    lookup: {
      group: "Collections",
      label: "Lookup",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
        from: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "From",
          type: "string",
        },
        localField: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Local field",
          type: "string",
        },
        foreignField: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Foreign field",
          type: "string",
        },
        as: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "As",
          type: "string",
        },
      },
      plan: "Pro Gold",
      returnType: "array",
    },
    lowercase: {
      group: "Text",
      label: "Lower-case",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    map: {
      group: "Collections",
      label: "Map",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
        expression: {
          defaultValue: true,
          isExpressionAllowed: true,
          label: "Expression",
          type: "any",
        },
      },
      plan: "Pro",
      returnType: "array",
    },
    max: {
      group: "Math",
      label: "Max",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<number>", "number"],
          label: "Array",
          type: "array<number>",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    millisecondsToHours: {
      group: "Conversion",
      label: "Milliseconds to hours",
      parameters: {
        milliseconds: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Milliseconds",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    millisecondsToMinutes: {
      group: "Conversion",
      label: "Milliseconds to minutes",
      parameters: {
        milliseconds: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Milliseconds",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    millisecondsToSeconds: {
      group: "Conversion",
      label: "Milliseconds to seconds",
      parameters: {
        milliseconds: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Milliseconds",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    min: {
      group: "Math",
      label: "Min",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<number>", "number"],
          label: "Array",
          type: "array<number>",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    minutesToHours: {
      group: "Conversion",
      label: "Minutes to hours",
      parameters: {
        minutes: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Minutes",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    minutesToMilliseconds: {
      group: "Conversion",
      label: "Minutes to milliseconds",
      parameters: {
        minutes: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Minutes",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    minutesToSeconds: {
      group: "Conversion",
      label: "Minutes to seconds",
      parameters: {
        minutes: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Minutes",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    multiply: {
      group: "Math",
      label: "Multiply",
      parameters: {
        values: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<number>", "number"],
          label: "Values",
          type: "array<number>",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    not: {
      group: "Logic",
      label: "Not",
      parameters: {
        value: {
          defaultValue: true,
          isExpressionAllowed: true,
          label: "Value",
          type: "boolean",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    now: {
      group: "Date & Time",
      label: "Now",
      parameters: {},
      plan: "Personal",
      returnType: "string",
    },
    object: {
      group: "Object",
      label: "Object",
      parameters: {
        fields: {
          defaultValue: {},
          isExpressionAllowed: true,
          itemType: "any",
          label: "Fields",
          type: "object",
        },
      },
      plan: "Pro",
      returnType: "object",
    },
    or: {
      group: "Logic",
      label: "Or",
      parameters: {
        values: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<boolean>", "boolean"],
          label: "Values",
          type: "array<boolean>",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    PI: {
      group: "Math",
      label: "PI",
      parameters: {},
      plan: "Personal",
      returnType: "number",
    },
    path: {
      group: "Object",
      label: "Path",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Value",
          type: "string",
        },
      },
      plan: "Pro",
      returnType: "any",
    },
    pipeline: {
      group: "Collections",
      label: "Pipeline",
      parameters: {
        input: {
          defaultValue: true,
          isExpressionAllowed: true,
          label: "Input",
          type: "any",
        },
        stages: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Stages",
          type: "array<any>",
        },
      },
      plan: "Pro Gold",
      returnType: "any",
    },
    platformUserEmail: {
      group: "Platform User",
      label: "Platform user e-mail",
      labelShort: "E-mail",
      parameters: {},
      plan: "Personal",
      returnType: "string",
    },
    pow: {
      description: "Returns the value of the provided base raised to the provided power.",
      group: "Math",
      label: "Pow",
      parameters: {
        base: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
        exponent: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    prop: {
      group: "Component",
      label: "Component property",
      labelShort: "Property",
      parameters: {
        componentId: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Component ID",
          type: "string",
        },
        prop: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Property",
          type: "string",
        },
      },
      plan: "Pro",
      returnType: "any",
    },
    radiansToDegrees: {
      group: "Conversion",
      label: "Radians to degrees",
      parameters: {
        radians: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Radians",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    random: {
      group: "Math",
      label: "Random",
      parameters: {
        min: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Min",
          type: "number",
        },
        max: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Max",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    range: {
      group: "Collections",
      label: "Range",
      parameters: {
        count: {
          defaultValue: 10,
          isExpressionAllowed: true,
          label: "Count",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "array<number>",
    },
    replace: {
      group: "Text",
      label: "Replace",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
        search: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Search",
          type: "string",
        },
        replace: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Replace",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    round: {
      group: "Math",
      label: "Round",
      parameters: {
        value: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    secondsToHours: {
      group: "Conversion",
      label: "Seconds to hours",
      parameters: {
        seconds: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Seconds",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    secondsToMilliseconds: {
      group: "Conversion",
      label: "Seconds to milliseconds",
      parameters: {
        seconds: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Seconds",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    secondsToMinutes: {
      group: "Conversion",
      label: "Seconds to minutes",
      parameters: {
        seconds: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Seconds",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    sin: {
      description: "Returns the sine of a number in radians.",
      group: "Math",
      label: "Sin",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    sinh: {
      description: "Returns the hyperbolic sine of a number.",
      group: "Math",
      label: "Sinh",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    socketData: {
      group: "Socket",
      label: "Socket data",
      labelShort: "Data",
      parameters: {},
      plan: "Pro Gold",
      returnType: "any",
    },
    socketDataArray: {
      group: "Socket",
      label: "Socket data array",
      labelShort: "Data array",
      parameters: {},
      plan: "Pro Gold",
      returnType: "array",
    },
    sort: {
      group: "Collections",
      label: "Sort",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Array",
          type: "array",
        },
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "any",
        },
        direction: {
          defaultValue: "asc",
          isExpressionAllowed: false,
          label: "Direction",
          options: [
            { label: "Ascending", value: "asc" },
            { label: "Descending", value: "desc" },
          ],
          type: "enum<string>",
        },
      },
      plan: "Pro",
      returnType: "array",
    },
    split: {
      group: "Text",
      label: "Split",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
        separator: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Separator",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "array<string>",
    },
    sqrt: {
      description: "Returns the square root of a number.",
      group: "Math",
      label: "Sqrt",
      parameters: {
        value: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    state: {
      group: "Object",
      label: "State",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Value",
          type: "string",
        },
      },
      plan: "Pro",
      returnType: "any",
    },
    stringLength: {
      group: "Text",
      label: "String length",
      labelShort: "Length",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    substring: {
      group: "Text",
      label: "Substring",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
        start: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Start",
          type: "number",
        },
        length: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Length",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    subtract: {
      group: "Math",
      label: "Subtract",
      parameters: {
        left: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Left",
          type: "number",
        },
        right: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Right",
          type: "number",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    sum: {
      group: "Math",
      label: "Sum",
      parameters: {
        array: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: ["array<number>", "number"],
          label: "Array",
          type: "array<number>",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    tan: {
      description: "Returns the tangent of a number in radians.",
      group: "Math",
      label: "Tan",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    tanh: {
      description: "Returns the hyperbolic tangent of a number.",
      group: "Math",
      label: "Tanh",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Value",
          type: "number",
        },
      },
      plan: "Pro",
      returnType: "number",
    },
    toArray: {
      group: "Conversion",
      label: "To array",
      parameters: {
        value: {
          defaultValue: [],
          isExpressionAllowed: true,
          label: "Value",
          type: "any",
        },
      },
      plan: "Personal",
      returnType: "array",
    },
    toBoolean: {
      group: "Conversion",
      label: "To boolean",
      parameters: {
        value: {
          defaultValue: false,
          isExpressionAllowed: true,
          label: "Value",
          type: "any",
        },
      },
      plan: "Personal",
      returnType: "boolean",
    },
    toNumber: {
      group: "Conversion",
      label: "To number",
      parameters: {
        value: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Value",
          type: "any",
        },
      },
      plan: "Personal",
      returnType: "number",
    },
    toObject: {
      group: "Conversion",
      label: "To object",
      parameters: {
        value: {
          defaultValue: {},
          isExpressionAllowed: true,
          label: "Value",
          type: "any",
        },
      },
      plan: "Personal",
      returnType: "object",
    },
    toString: {
      group: "Text",
      label: "To string",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "any",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    trim: {
      group: "Text",
      label: "Trim",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    uppercase: {
      group: "Text",
      label: "Upper-case",
      parameters: {
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "string",
        },
      },
      plan: "Personal",
      returnType: "string",
    },
    userEmail: {
      group: "User",
      label: "User e-mail",
      labelShort: "E-mail",
      parameters: {},
      plan: "Pro Gold",
      returnType: "string",
    },
    userName: {
      group: "User",
      label: "User name",
      labelShort: "Name",
      parameters: {},
      plan: "Pro Gold",
      returnType: "string",
    },
    viewportHeight: {
      group: "Viewport",
      label: "Viewport height",
      labelShort: "Height",
      parameters: {},
      plan: "Personal",
      returnType: "number",
    },
    viewportOrientation: {
      group: "Viewport",
      label: "Viewport orientation",
      labelShort: "Orientation",
      parameters: {},
      plan: "Personal",
      returnType: "string",
    },
    viewportWidth: {
      group: "Viewport",
      label: "Viewport width",
      labelShort: "Width",
      parameters: {},
      plan: "Personal",
      returnType: "number",
    },
    websiteDescription: {
      group: "Website",
      label: "Website description",
      labelShort: "Description",
      parameters: {},
      plan: "Personal",
      returnType: "string",
    },
    websiteLanguage: {
      group: "Website",
      label: "Website language",
      labelShort: "Language",
      parameters: {},
      plan: "Personal",
      returnType: "string",
    },
    websiteName: {
      group: "Website",
      label: "Website name",
      labelShort: "Name",
      parameters: {},
      plan: "Personal",
      returnType: "string",
    },
  };
}
