// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

export function createCanvasSchema() {
  return {
    defaultSlots: {},
    description: "A programmable canvas that can be used to create interactive experiences, tools or games.",
    editor: {
      defaultOpenGroups: {
        action: ["Action"],
        layout: ["Size"],
        selectors: ["Selectors"],
        styling: ["Surface", "Border"],
        visibility: ["Visibility"],
      },
      roleGroupOrder: {
        action: ["Action"],
        layout: ["Size"],
        selectors: ["Selectors"],
        styling: ["Surface", "Border", "Effects"],
        visibility: ["Visibility"],
      },
      roleOrder: ["styling", "layout", "action", "visibility", "selectors"],
    },
    exportCSS: (canvas = null, canvasSchema = null) => {
      return "";
    },
    exportHTML: (canvas, canvasSchema, pageSchema, indentation) => {
      return "";
    },
    isAllowingChildComponents: false,
    label: "Canvas",
    plan: "Pro Gold",
    props: {
      backgroundColor: {
        cssProperty: "background-color",
        cssVariableName: "--canvas-background-color",
        defaultValue: "var(--pc-semantic-surface-base)",
        label: "Background color",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "color",
      },
      borderColor: {
        cssProperty: "border-color",
        cssVariableName: "--canvas-border-color",
        defaultValue: "var(--pc-semantic-border-default)",
        label: "Border color",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "color",
      },
      borderRadius: {
        cssProperty: "border-radius",
        cssVariableName: "--canvas-border-radius",
        defaultValue: "8px",
        label: "Border radius",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      borderWidth: {
        cssProperty: "border-width",
        cssVariableName: "--canvas-border-width",
        defaultValue: "1px",
        label: "Border width",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      borderStyle: {
        cssProperty: "border-style",
        cssVariableName: "--canvas-border-style",
        defaultValue: "solid",
        label: "Border style",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      boxShadow: {
        cssProperty: "box-shadow",
        cssVariableName: "--canvas-box-shadow",
        defaultValue: "var(--pc-semantic-shadow-sm)",
        label: "Box shadow",
        role: "styling",
        roleGroup: "Effects",
        schemaType: "string",
        type: "text",
      },
      width: {
        cssProperty: "width",
        cssVariableName: "--canvas-width",
        defaultValue: "100%",
        label: "Width",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      height: {
        cssProperty: "height",
        cssVariableName: "--canvas-height",
        defaultValue: "500px",
        label: "Height",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      onMouseDown: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: null,
        label: "On mouse down",
        role: "action",
        roleGroup: "Action",
        schemaType: "object",
        type: "action",
      },
      onMouseMove: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: null,
        label: "On mouse move",
        role: "action",
        roleGroup: "Action",
        schemaType: "object",
        type: "action",
      },
      onMouseUp: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: null,
        label: "On mouse up",
        role: "action",
        roleGroup: "Action",
        schemaType: "object",
        type: "action",
      },
      onRender: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: null,
        label: "On render",
        role: "action",
        roleGroup: "Action",
        schemaType: "object",
        type: "action",
      },
      onUpdate: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: null,
        label: "On update",
        role: "action",
        roleGroup: "Action",
        schemaType: "object",
        type: "action",
      },
      isVisible: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: true,
        label: "Is visible",
        role: "visibility",
        roleGroup: "Visibility",
        schemaType: "boolean",
        type: "switch",
      },
      selectors: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: [],
        label: "Selectors",
        role: "selectors",
        roleGroup: "Selectors",
        schemaType: "array",
        type: "selectors",
      },
    },
    slots: {},
  };
}
