// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

export function createRichTextSchema() {
  return {
    defaultSlots: {},
    description: "A rich-text editor and viewer with support for text styles and headings among other things.",
    editor: {
      defaultOpenGroups: {
        content: ["Content"],
        layout: [],
        selectors: [],
        styling: [],
      },
      roleGroupOrder: {
        content: ["Content"],
        layout: ["Spacing"],
        selectors: ["Selectors"],
        styling: ["Surface", "Border"],
      },
      roleOrder: ["content", "styling", "layout", "selectors"],
    },
    exportCSS: (richText = null, richTextSchema = null) => {
      return "";
    },
    exportHTML: (richText, richTextSchema, pageSchema, indentation) => {
      return "";
    },
    isAllowingChildComponents: false,
    label: "Rich text",
    plan: "Pro",
    props: {
      value: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "<p>Hello World!</p>",
        label: "Value",
        role: "content",
        roleGroup: "Content",
        schemaType: "string",
        type: "textarea",
      },
      editable: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: true,
        label: "Editable",
        role: "content",
        roleGroup: "Content",
        schemaType: "boolean",
        type: "switch",
      },
      backgroundColor: {
        cssProperty: "background-color",
        cssVariableName: "--rich-text-background-color",
        defaultValue: "var(--pc-semantic-surface-page)",
        label: "Background color",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "color",
      },
      backgroundColorContent: {
        cssProperty: "background-color",
        cssVariableName: "--rich-text-background-color-content",
        defaultValue: "var(--pc-semantic-surface-base)",
        label: "Background color - Content",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "color",
      },
      boxShadow: {
        cssProperty: "box-shadow",
        cssVariableName: "--rich-text-box-shadow",
        defaultValue: "none",
        label: "Box shadow",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      boxShadowFocus: {
        cssProperty: "box-shadow",
        cssVariableName: "--rich-text-box-shadow-focus",
        defaultValue: "var(--pc-semantic-focus-ring)",
        label: "Box shadow - Focus",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      borderWidth: {
        cssProperty: "border-width",
        cssVariableName: "--rich-text-border-width",
        defaultValue: "1px",
        label: "Border width",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      borderColor: {
        cssProperty: "border-color",
        cssVariableName: "--rich-text-border-color",
        defaultValue: "var(--pc-semantic-border-default)",
        label: "Border color",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "color",
      },
      borderRadius: {
        cssProperty: "border-radius",
        cssVariableName: "--rich-text-border-radius",
        defaultValue: "8px",
        label: "Border radius",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      padding: {
        cssProperty: "padding",
        cssVariableName: "--rich-text-padding",
        defaultValue: "0.25rem",
        label: "Padding",
        role: "layout",
        roleGroup: "Spacing",
        schemaType: "string",
        type: "text",
      },
      marginContent: {
        cssProperty: "margin",
        cssVariableName: "--rich-text-margin-content",
        defaultValue: "1rem",
        label: "Margin - Content",
        role: "layout",
        roleGroup: "Spacing",
        schemaType: "string",
        type: "text",
      },
      selectors: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: [],
        label: "Selectors",
        role: "selectors",
        roleGroup: "Selectors",
        schemaType: "array",
        type: "selectors",
      },
    },
    slots: {},
  };
}
