// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

export function getActionSchema() {
  return {
    addStateValue: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "State",
      label: "Add state value",
      labelShort: "Add value",
      parameters: {
        path: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Path",
          type: "string",
        },
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "any",
        },
      },
      plan: "Pro",
    },
    canvasCircle: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas circle",
      labelShort: "Circle",
      parameters: {
        x: {
          defaultValue: 100,
          isExpressionAllowed: true,
          label: "X",
          type: "number",
        },
        y: {
          defaultValue: 100,
          isExpressionAllowed: true,
          label: "Y",
          type: "number",
        },
        radius: {
          defaultValue: 50,
          isExpressionAllowed: true,
          label: "Radius",
          type: "number",
        },
        fill: {
          defaultValue: "#000000",
          isExpressionAllowed: true,
          label: "Fill",
          type: "string",
        },
        stroke: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Stroke",
          type: "string",
        },
        strokeWidth: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Stroke width",
          type: "number",
        },
        opacity: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Opacity",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    canvasClear: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas clear",
      labelShort: "Clear",
      parameters: {},
      plan: "Pro Gold",
    },
    canvasImage: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas image",
      labelShort: "Image",
      parameters: {
        src: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Source",
          type: "string",
        },
        x: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "X",
          type: "number",
        },
        y: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Y",
          type: "number",
        },
        width: {
          defaultValue: 100,
          isExpressionAllowed: true,
          label: "Width",
          type: "number",
        },
        height: {
          defaultValue: 100,
          isExpressionAllowed: true,
          label: "Height",
          type: "number",
        },
        opacity: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Opacity",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    canvasLine: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas line",
      labelShort: "Line",
      parameters: {
        x1: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "X1",
          type: "number",
        },
        y1: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Y1",
          type: "number",
        },
        x2: {
          defaultValue: 100,
          isExpressionAllowed: true,
          label: "X2",
          type: "number",
        },
        y2: {
          defaultValue: 100,
          isExpressionAllowed: true,
          label: "Y2",
          type: "number",
        },
        stroke: {
          defaultValue: "#000000",
          isExpressionAllowed: true,
          label: "Stroke",
          type: "string",
        },
        strokeWidth: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Stroke width",
          type: "number",
        },
        opacity: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Opacity",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    canvasPolygon: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas polygon",
      labelShort: "Polygon",
      parameters: {
        points: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "object",
          label: "Points",
          type: "array<object>",
        },
        fill: {
          defaultValue: "#000000",
          isExpressionAllowed: true,
          label: "Fill",
          type: "string",
        },
        stroke: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Stroke",
          type: "string",
        },
        strokeWidth: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Stroke width",
          type: "number",
        },
        opacity: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Opacity",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    canvasRectangle: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas rectangle",
      labelShort: "Rectangle",
      parameters: {
        x: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "X",
          type: "number",
        },
        y: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Y",
          type: "number",
        },
        width: {
          defaultValue: 100,
          isExpressionAllowed: true,
          label: "Width",
          type: "number",
        },
        height: {
          defaultValue: 100,
          isExpressionAllowed: true,
          label: "Height",
          type: "number",
        },
        fill: {
          defaultValue: "#000000",
          isExpressionAllowed: true,
          label: "Fill",
          type: "string",
        },
        stroke: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Stroke",
          type: "string",
        },
        strokeWidth: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Stroke width",
          type: "number",
        },
        opacity: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Opacity",
          type: "number",
        },
        radius: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Radius",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    canvasRestore: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas restore",
      labelShort: "Restore",
      parameters: {},
      plan: "Pro Gold",
    },
    canvasRotate: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas rotate",
      labelShort: "Rotate",
      parameters: {
        angle: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Angle",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    canvasSave: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas save",
      labelShort: "Save",
      parameters: {},
      plan: "Pro Gold",
    },
    canvasScale: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas scale",
      labelShort: "Scale",
      parameters: {
        x: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "X",
          type: "number",
        },
        y: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Y",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    canvasText: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas text",
      labelShort: "Text",
      parameters: {
        text: {
          defaultValue: "Hello!",
          isExpressionAllowed: true,
          label: "Text",
          type: "string",
        },
        x: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "X",
          type: "number",
        },
        y: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Y",
          type: "number",
        },
        color: {
          defaultValue: "#000000",
          isExpressionAllowed: true,
          label: "Color",
          type: "string",
        },
        fontSize: {
          defaultValue: 16,
          isExpressionAllowed: true,
          label: "Font size",
          type: "number",
        },
        fontFamily: {
          defaultValue: "sans-serif",
          isExpressionAllowed: true,
          label: "Font family",
          type: "string",
        },
        fontWeight: {
          defaultValue: "normal",
          isExpressionAllowed: true,
          label: "Font weight",
          type: "string",
        },
        align: {
          defaultValue: "left",
          isExpressionAllowed: true,
          label: "Align",
          type: "string",
        },
        opacity: {
          defaultValue: 1,
          isExpressionAllowed: true,
          label: "Opacity",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    canvasTranslate: {
      componentType: "Canvas",
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Canvas",
      label: "Canvas translate",
      labelShort: "Translate",
      parameters: {
        x: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "X",
          type: "number",
        },
        y: {
          defaultValue: 0,
          isExpressionAllowed: true,
          label: "Y",
          type: "number",
        },
      },
      plan: "Pro Gold",
    },
    forEach: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Flow Control",
      label: "For each",
      parameters: {
        items: {
          defaultValue: [],
          isExpressionAllowed: true,
          itemType: "any",
          label: "Items",
          type: "array",
        },
      },
      plan: "Pro",
    },
    if: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Flow Control",
      label: "If",
      parameters: {
        condition: {
          defaultValue: true,
          isExpressionAllowed: true,
          label: "Condition",
          type: "boolean",
        },
      },
      plan: "Pro",
    },
    navigate: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Navigation",
      label: "Navigate",
      parameters: {
        to: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "To",
          type: "string",
        },
      },
      plan: "Pro",
    },
    print: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Debugging",
      label: "Print",
      parameters: {
        data: {
          defaultValue: {},
          isExpressionAllowed: true,
          itemType: "any",
          label: "Data",
          type: "object",
        },
      },
      plan: "Pro",
    },
    socketBroadcast: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Socket",
      label: "Socket broadcast",
      labelShort: "Broadcast",
      parameters: {
        data: {
          defaultValue: {},
          isExpressionAllowed: true,
          itemType: "any",
          label: "Data",
          type: "object",
        },
      },
      plan: "Pro Gold",
    },
    socketConnect: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Socket",
      label: "Socket connect",
      labelShort: "Connect",
      parameters: {},
      plan: "Pro Gold",
    },
    socketDataAdd: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Socket",
      label: "Socket data add",
      labelShort: "Data add",
      parameters: {
        data: {
          defaultValue: {},
          isExpressionAllowed: true,
          itemType: "any",
          label: "Data",
          type: "object",
        },
      },
      plan: "Pro Gold",
    },
    socketDataClear: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Socket",
      label: "Socket data clear",
      labelShort: "Data clear",
      parameters: {},
      plan: "Pro Gold",
    },
    socketDataRemove: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Socket",
      label: "Socket data remove",
      labelShort: "Data remove",
      parameters: {
        data: {
          defaultValue: {},
          isExpressionAllowed: true,
          itemType: "any",
          label: "Data",
          type: "object",
        },
      },
      plan: "Pro Gold",
    },
    socketDisconnect: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Socket",
      label: "Socket disconnect",
      labelShort: "Disconnect",
      parameters: {},
      plan: "Pro Gold",
    },
    socketEmit: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Socket",
      label: "Socket emit",
      labelShort: "Emit",
      parameters: {
        room: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Room",
          type: "string",
        },
        data: {
          defaultValue: {},
          isExpressionAllowed: true,
          itemType: "any",
          label: "Data",
          type: "object",
        },
      },
      plan: "Pro Gold",
    },
    setStateValue: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "State",
      label: "Set state value",
      labelShort: "Set value",
      parameters: {
        path: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Path",
          type: "string",
        },
        value: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Value",
          type: "any",
        },
      },
      plan: "Pro",
    },
    updateComponent: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Component",
      label: "Update component",
      labelShort: "Update",
      parameters: {
        componentId: {
          defaultValue: "",
          isExpressionAllowed: false,
          label: "Component ID",
          type: "string",
        },
        data: {
          defaultValue: {},
          isExpressionAllowed: true,
          itemType: "any",
          label: "Data",
          type: "object",
        },
      },
      plan: "Pro",
    },
    userSignIn: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "User",
      label: "User sign in",
      labelShort: "Sign in",
      parameters: {
        email: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "E-mail",
          type: "string",
        },
        password: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Password",
          type: "string",
        },
      },
      plan: "Pro Gold",
    },
    userSignOut: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "User",
      label: "User sign out",
      labelShort: "Sign out",
      parameters: {},
      plan: "Pro Gold",
    },
    userSignUp: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "User",
      label: "User sign up",
      labelShort: "Sign up",
      parameters: {
        email: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "E-mail",
          type: "string",
        },
        password: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Password",
          type: "string",
        },
        name: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Name",
          type: "string",
        },
        code: {
          defaultValue: "",
          isExpressionAllowed: true,
          label: "Code",
          type: "string",
        },
      },
      plan: "Pro Gold",
    },
    wait: {
      condition: {
        defaultValue: true,
        isExpressionAllowed: true,
        label: "Condition",
        type: "boolean",
      },
      group: "Flow Control",
      label: "Wait",
      parameters: {
        delay: {
          defaultValue: 0,
          isExpressionAllowed: false,
          label: "Delay",
          type: "number",
        },
      },
      plan: "Pro",
    },
  };
}
