// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

export function createMapSchema() {
  return {
    defaultSlots: {},
    description: "A map that uses tiles from OpenStreetMap by default.",
    editor: {
      defaultOpenGroups: {
        content: ["Content"],
        layout: [],
        privacy: [],
        selectors: [],
        styling: ["Surface"],
      },
      roleGroupOrder: {
        content: ["Content"],
        layout: ["Size", "Context menu", "Context menu button"],
        privacy: ["Privacy"],
        selectors: ["Selectors"],
        styling: ["Surface", "Context menu", "Context menu button"],
      },
      roleOrder: ["content", "styling", "layout", "selectors", "privacy"],
    },
    exportCSS: (map = null, mapSchema = null) => {
      return "";
    },
    exportHTML: (map, mapSchema, sideSchema, indentation) => {
      return "";
    },
    isAllowingChildComponents: false,
    label: "Map",
    plan: "Pro",
    props: {
      centerLatitude: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: 55.60930927366408,
        label: "Center - Latitude",
        role: "content",
        roleGroup: "Content",
        schemaType: "number",
        type: "number",
      },
      centerLongitude: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: 12.999911968422987,
        label: "Center - Longitude",
        role: "content",
        roleGroup: "Content",
        schemaType: "number",
        type: "number",
      },
      centerPopupContent: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "",
        label: "Center - Popup content",
        role: "content",
        roleGroup: "Content",
        schemaType: "string",
        type: "textarea",
      },
      scrollWheelZoom: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: true,
        label: "Scroll wheel zoom",
        role: "content",
        roleGroup: "Content",
        schemaType: "boolean",
        type: "switch",
      },
      zoom: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: 10,
        label: "Zoom",
        role: "content",
        roleGroup: "Content",
        schemaType: "number",
        type: "number",
      },
      attribution: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | &copy; <a href="https://leafletjs.com">Leaflet</a>',
        label: "Attribution",
        role: "content",
        roleGroup: "Content",
        schemaType: "string",
        type: "text",
      },
      url: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",
        label: "URL",
        role: "content",
        roleGroup: "Content",
        schemaType: "string",
        type: "text",
      },
      borderWidth: {
        cssProperty: "border-width",
        cssVariableName: "--map-border-width",
        defaultValue: "5px",
        label: "Border width",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      borderColor: {
        cssProperty: "border-color",
        cssVariableName: "--map-border-color",
        defaultValue: "var(--pc-semantic-border-secondary)",
        label: "Border color",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "color",
      },
      borderRadius: {
        cssProperty: "border-radius",
        cssVariableName: "--map-border-radius",
        defaultValue: "8px",
        label: "Border radius",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      boxShadow: {
        cssProperty: "box-shadow",
        cssVariableName: "--map-box-shadow",
        defaultValue: "var(--pc-semantic-shadow-sm)",
        label: "Box shadow",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      contextMenuBackgroundColor: {
        cssProperty: "background-color",
        cssVariableName: "--map-context-menu-background-color",
        defaultValue: "var(--pc-semantic-surface-base)",
        label: "Background color",
        role: "styling",
        roleGroup: "Context menu",
        schemaType: "string",
        type: "color",
      },
      contextMenuBorderWidth: {
        cssProperty: "border-width",
        cssVariableName: "--map-context-menu-border-width",
        defaultValue: "1px",
        label: "Border width",
        role: "styling",
        roleGroup: "Context menu",
        schemaType: "string",
        type: "text",
      },
      contextMenuBorderColor: {
        cssProperty: "border-color",
        cssVariableName: "--map-context-menu-border-color",
        defaultValue: "var(--pc-semantic-border-default)",
        label: "Border color",
        role: "styling",
        roleGroup: "Context menu",
        schemaType: "string",
        type: "color",
      },
      contextMenuBorderRadius: {
        cssProperty: "border-radius",
        cssVariableName: "--map-context-menu-border-radius",
        defaultValue: "4px",
        label: "Border radius",
        role: "styling",
        roleGroup: "Context menu",
        schemaType: "string",
        type: "text",
      },
      contextMenuBoxShadow: {
        cssProperty: "box-shadow",
        cssVariableName: "--map-context-menu-box-shadow",
        defaultValue: "var(--pc-semantic-shadow-sm)",
        label: "Box shadow",
        role: "styling",
        roleGroup: "Context menu",
        schemaType: "string",
        type: "text",
      },
      contextMenuButtonBackgroundColor: {
        cssProperty: "background-color",
        cssVariableName: "--map-context-menu-button-background-color",
        defaultValue: "transparent",
        label: "Background color",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonBackgroundColorHover: {
        cssProperty: "background-color",
        cssVariableName: "--map-context-menu-button-background-color-hover",
        defaultValue: "transparent",
        label: "Background color - Hover",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonBackgroundColorSelected: {
        cssProperty: "background-color",
        cssVariableName: "--map-context-menu-button-background-color-selected",
        defaultValue: "var(--pc-semantic-interactive-primary)",
        label: "Background color - Selected",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonBackgroundColorSelectedHover: {
        cssProperty: "background-color",
        cssVariableName: "--map-context-menu-button-background-color-selected-hover",
        defaultValue: "var(--pc-semantic-interactive-primary-hover)",
        label: "Background color - Selected - Hover",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonBorderWidth: {
        cssProperty: "border-width",
        cssVariableName: "--map-context-menu-button-border-width",
        defaultValue: "1px",
        label: "Border width",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "text",
      },
      contextMenuButtonBorderColor: {
        cssProperty: "border-color",
        cssVariableName: "--map-context-menu-button-border-color",
        defaultValue: "transparent",
        label: "Border color",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonBorderColorHover: {
        cssProperty: "border-color",
        cssVariableName: "--map-context-menu-button-border-color-hover",
        defaultValue: "transparent",
        label: "Border color - Hover",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonBorderColorSelected: {
        cssProperty: "border-color",
        cssVariableName: "--map-context-menu-button-border-color-selected",
        defaultValue: "transparent",
        label: "Border color - Selected",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonBorderColorSelectedHover: {
        cssProperty: "border-color",
        cssVariableName: "--map-context-menu-button-border-color-selected-hover",
        defaultValue: "transparent",
        label: "Border color",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonBorderRadius: {
        cssProperty: "border-radius",
        cssVariableName: "--map-context-menu-button-border-radius",
        defaultValue: "4px",
        label: "Border radius",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "text",
      },
      contextMenuButtonColor: {
        cssProperty: "color",
        cssVariableName: "--map-context-menu-button-color",
        defaultValue: "var(--pc-semantic-text-primary)",
        label: "Color",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonColorHover: {
        cssProperty: "color",
        cssVariableName: "--map-context-menu-button-color-hover",
        defaultValue: "var(--pc-semantic-interactive-primary)",
        label: "Color - Hover",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonColorSelected: {
        cssProperty: "color",
        cssVariableName: "--map-context-menu-button-color-selected",
        defaultValue: "var(--pc-semantic-text-inverse)",
        label: "Color - Selected",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      contextMenuButtonColorSelectedHover: {
        cssProperty: "color",
        cssVariableName: "--map-context-menu-button-color-selected-hover",
        defaultValue: "var(--pc-semantic-text-inverse)",
        label: "Color - Selected - Hover",
        role: "styling",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "color",
      },
      width: {
        cssProperty: "width",
        cssVariableName: "--map-width",
        defaultValue: "100%",
        label: "Width",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      minWidth: {
        cssProperty: "min-width",
        cssVariableName: "--map-min-width",
        defaultValue: "0px",
        label: "Minimum width",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      maxWidth: {
        cssProperty: "max-width",
        cssVariableName: "--map-max-width",
        defaultValue: "none",
        label: "Maximum width",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      height: {
        cssProperty: "height",
        cssVariableName: "--map-height",
        defaultValue: "400px",
        label: "Height",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      minHeight: {
        cssProperty: "min-height",
        cssVariableName: "--map-min-height",
        defaultValue: "0px",
        label: "Minimum height",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      maxHeight: {
        cssProperty: "max-height",
        cssVariableName: "--map-max-height",
        defaultValue: "none",
        label: "Maximum height",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      contextMenuGap: {
        cssProperty: "gap",
        cssVariableName: "--map-context-menu-gap",
        defaultValue: "1rem",
        label: "Gap",
        role: "layout",
        roleGroup: "Context menu",
        schemaType: "string",
        type: "text",
      },
      contextMenuPadding: {
        cssProperty: "padding",
        cssVariableName: "--map-context-menu-padding",
        defaultValue: "1rem",
        label: "Padding",
        role: "layout",
        roleGroup: "Context menu",
        schemaType: "string",
        type: "text",
      },
      contextMenuButtonGap: {
        cssProperty: "gap",
        cssVariableName: "--map-context-menu-button-gap",
        defaultValue: "1rem",
        label: "Gap",
        role: "layout",
        roleGroup: "Context menu button",
        schemaType: "string",
        type: "text",
      },
      selectors: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: [],
        label: "Selectors",
        role: "selectors",
        roleGroup: "Selectors",
        schemaType: "array",
        type: "selectors",
      },
      consent: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "functional",
        label: "Requires consent",
        options: [
          { label: "None", value: "" },
          { label: "Functional", value: "functional" },
          { label: "Analytics", value: "analytics" },
          { label: "Marketing", value: "marketing" },
        ],
        role: "privacy",
        roleGroup: "Privacy",
        schemaType: "array",
        type: "select",
      },
    },
    slots: {},
  };
}
