// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

import { exportCSSFromProps } from "../runtime/export/exportCSSFromProps";

export function createIconSchema() {
  return {
    description: "",
    editor: {
      defaultOpenGroups: {
        content: ["Content"],
        selectors: [],
        styling: ["Typography"],
        visibility: [],
      },
      roleGroupOrder: {
        content: ["Content"],
        selectors: ["Selectors"],
        styling: ["Typography", "Surface"],
        visibility: ["Visibility"],
      },
      roleOrder: ["content", "styling", "visibility", "selectors"],
    },
    exportCSS: (icon = null, iconSchema = null) => {
      return "";
    },
    exportHTML: (icon, iconSchema, pageSchema, indentation) => {
      return "";
    },
    isAllowingChildComponents: true,
    label: "Icon",
    plan: "Pro",
    props: {
      icon: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: "fa-question",
        label: "Icon",
        options: [
          { label: "Add", value: "fa-add" },
          { label: "Align - Center", value: "fa-align-center" },
          { label: "Align - Justify", value: "fa-align-justify" },
          { label: "Align - Left", value: "fa-align-left" },
          { label: "Align - Right", value: "fa-align-right" },
          { label: "Arrow - Right", value: "fa-arrow-right" },
          { label: "Backward", value: "fa-backward" },
          { label: "Bolt", value: "fa-bolt" },
          { label: "Brackets - Curly", value: "fa-brackets-curly" },
          { label: "Browser", value: "fa-browser" },
          { label: "Bug", value: "fa-bug" },
          { label: "Calculator", value: "fa-calculator" },
          { label: "Cancel", value: "fa-cancel" },
          { label: "Check", value: "fa-check" },
          { label: "Chevron - Circle - Left", value: "fa-chevron-circle-left" },
          { label: "Chevron - Down", value: "fa-chevron-down" },
          { label: "Chevron - Left", value: "fa-chevron-left" },
          { label: "Chevron - Right", value: "fa-chevron-right" },
          { label: "Chevron - Up", value: "fa-chevron-up" },
          { label: "Circle", value: "fa-circle" },
          { label: "Clock", value: "fa-clock" },
          { label: "Clock - Rotate left", value: "fa-clock-rotate-left" },
          { label: "Close", value: "fa-close" },
          { label: "Cloud", value: "fa-cloud" },
          { label: "Code", value: "fa-code" },
          { label: "Code branch", value: "fa-code-branch" },
          { label: "Cog", value: "fa-cog" },
          { label: "Cookie", value: "fa-cookie" },
          { label: "Copy", value: "fa-copy" },
          { label: "Crop", value: "fa-crop" },
          { label: "Cubes", value: "fa-cubes" },
          { label: "Dashboard", value: "fa-dashboard" },
          { label: "Database", value: "fa-database" },
          { label: "Diagram - Project", value: "fa-diagram-project" },
          { label: "Divide", value: "fa-divide" },
          { label: "Down", value: "fa-down" },
          { label: "Edit", value: "fa-edit" },
          { label: "Exchange", value: "fa-exchange" },
          { label: "Eye", value: "fa-eye" },
          { label: "File - Contract", value: "fa-file-contract" },
          { label: "File - Export", value: "fa-file-export" },
          { label: "File - HTML", value: "fa-file-html" },
          { label: "File - Lines", value: "fa-file-lines" },
          { label: "Font", value: "fa-font" },
          { label: "Forward", value: "fa-forward" },
          { label: "Gauge", value: "fa-gauge" },
          { label: "Gauge - High", value: "fa-gauge-high" },
          { label: "GitHub", value: "fa-github" },
          { label: "Globe", value: "fa-globe" },
          { label: "Handshake", value: "fa-handshake" },
          { label: "Image", value: "fa-image" },
          { label: "Images", value: "fa-images" },
          { label: "Layer group", value: "fa-layer-group" },
          { label: "Link slash", value: "fa-link-slash" },
          { label: "Mobile screen", value: "fa-mobile-screen" },
          { label: "Multiply", value: "fa-multiply" },
          { label: "Object group", value: "fa-object-group" },
          { label: "Page", value: "fa-page" },
          { label: "Palette", value: "fa-palette" },
          { label: "Paste", value: "fa-paste" },
          { label: "Plus", value: "fa-plus" },
          { label: "Puzzle piece", value: "fa-puzzle-piece" },
          { label: "Question", value: "fa-question" },
          { label: "Random", value: "fa-random" },
          { label: "Redo", value: "fa-redo" },
          { label: "Rectangle", value: "fa-rectangle" },
          { label: "Refresh", value: "fa-refresh" },
          { label: "Right / Left", value: "fa-right-left" },
          { label: "Rocket launch", value: "fa-rocket-launch" },
          { label: "Save", value: "fa-save" },
          { label: "Server", value: "fa-server" },
          { label: "Shapes", value: "fa-shapes" },
          { label: "Shield", value: "fa-shield" },
          { label: "Sign in", value: "fa-sign-in" },
          { label: "Sign out", value: "fa-sign-out" },
          { label: "Sparkles", value: "fa-sparkles" },
          { label: "Square root", value: "fa-square-root" },
          { label: "Square root - Variable", value: "fa-square-root-variable" },
          { label: "Subtract", value: "fa-subtract" },
          { label: "Table", value: "fa-table" },
          { label: "Table cells - Large", value: "fa-table-cells-large" },
          { label: "Table layout", value: "fa-table-layout" },
          { label: "Tower broadcast", value: "fa-tower-broadcast" },
          { label: "Trash", value: "fa-trash" },
          { label: "Triangle - Exclamation", value: "fa-triangle-exclamation" },
          { label: "Undo", value: "fa-undo" },
          { label: "Up", value: "fa-up" },
          { label: "Upload", value: "fa-upload" },
          { label: "User", value: "fa-user" },
          { label: "User gear", value: "fa-user-gear" },
          { label: "Users", value: "fa-users" },
          { label: "Wrench", value: "fa-wrench" },
        ],
        role: "content",
        roleGroup: "Content",
        schemaType: "enum<string>",
        type: "select",
      },
      color: {
        cssProperty: "color",
        cssVariableName: "--icon-color",
        defaultValue: "inherit",
        label: "Color",
        role: "styling",
        roleGroup: "Typography",
        schemaType: "string",
        type: "color",
      },
      colorHover: {
        cssProperty: "color",
        cssVariableName: "--icon-color-hover",
        defaultValue: "inherit",
        label: "Color - Hover",
        role: "styling",
        roleGroup: "Typography",
        schemaType: "string",
        type: "color",
      },
      cursor: {
        cssProperty: "cursor",
        cssVariableName: "--icon-cursor",
        defaultValue: "auto",
        label: "Cursor",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      isVisible: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: true,
        isExpressionUnsupported: true,
        label: "Is visible",
        role: "visibility",
        roleGroup: "Visibility",
        schemaType: "boolean",
        type: "switch",
      },
      selectors: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: [],
        label: "Selectors",
        role: "selectors",
        roleGroup: "Selectors",
        schemaType: "array",
        type: "selectors",
      },
    },
    slots: {},
  };
}
