// Copyright (C) 2026 Jörgen Lundgren <joergen.lundgren@macroing.org>
// SPDX-License-Identifier: AGPL-3.0-only

import { exportCSSFromProps } from "../runtime/export/exportCSSFromProps";

export function createMarqueeSchema() {
  return {
    defaultSlots: {
      body: [],
    },
    description: "",
    editor: {
      defaultOpenGroups: {
        content: ["Content"],
        layout: ["Spacing"],
        selectors: [],
        styling: [],
        visibility: [],
      },
      roleGroupOrder: {
        content: ["Content"],
        layout: ["Size", "Spacing"],
        selectors: ["Selectors"],
        styling: ["Surface", "Border"],
        visibility: ["Visibility"],
      },
      roleOrder: ["content", "layout", "styling", "visibility", "selectors"],
    },
    exportCSS: (marquee = null, marqueeSchema = null) => {
      return "";
    },
    exportHTML: (marquee, marqueeSchema, pageSchema, indentation) => {
      return "";
    },
    isAllowingChildComponents: true,
    label: "Marquee",
    plan: "Pro",
    props: {
      duration: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: 20,
        label: "Duration",
        role: "content",
        roleGroup: "Content",
        schemaType: "number",
        type: "number",
      },
      isPausingOnHover: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: true,
        label: "Is pausing on hover",
        role: "content",
        roleGroup: "Content",
        schemaType: "boolean",
        type: "switch",
      },
      width: {
        cssProperty: "width",
        cssVariableName: "--marquee-width",
        defaultValue: "100%",
        label: "Width",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      minWidth: {
        cssProperty: "min-width",
        cssVariableName: "--marquee-min-width",
        defaultValue: "auto",
        label: "Minimum width",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      maxWidth: {
        cssProperty: "max-width",
        cssVariableName: "--marquee-max-width",
        defaultValue: "none",
        label: "Maximum width",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      height: {
        cssProperty: "height",
        cssVariableName: "--marquee-height",
        defaultValue: "auto",
        label: "Height",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      minHeight: {
        cssProperty: "min-height",
        cssVariableName: "--marquee-min-height",
        defaultValue: "auto",
        label: "Minimum height",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      maxHeight: {
        cssProperty: "max-height",
        cssVariableName: "--marquee-max-height",
        defaultValue: "none",
        label: "Maximum height",
        role: "layout",
        roleGroup: "Size",
        schemaType: "string",
        type: "text",
      },
      gap: {
        cssProperty: "gap",
        cssVariableName: "--marquee-gap",
        defaultValue: "1rem",
        label: "Gap",
        role: "layout",
        roleGroup: "Spacing",
        schemaType: "string",
        type: "text",
      },
      margin: {
        cssProperty: "margin",
        cssVariableName: "--marquee-margin",
        defaultValue: "0px",
        label: "Margin",
        role: "layout",
        roleGroup: "Spacing",
        schemaType: "string",
        type: "text",
      },
      padding: {
        cssProperty: "padding",
        cssVariableName: "--marquee-padding",
        defaultValue: "clamp(1rem, 3vw, 4rem)",
        label: "Padding",
        role: "layout",
        roleGroup: "Spacing",
        schemaType: "string",
        type: "text",
      },
      backgroundColor: {
        cssProperty: "background-color",
        cssVariableName: "--marquee-background-color",
        defaultValue: "initial",
        label: "Background color",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "color",
      },
      background: {
        cssProperty: "background",
        cssVariableName: "--marquee-background",
        defaultValue: "none",
        label: "Background",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      backgroundImage: {
        cssProperty: "background-image",
        cssVariableName: "--marquee-background-image",
        defaultValue: "initial",
        label: "Background image",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      backgroundSize: {
        cssProperty: "background-size",
        cssVariableName: "--marquee-background-size",
        defaultValue: "initial",
        label: "Background size",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      backgroundPosition: {
        cssProperty: "background-position",
        cssVariableName: "--marquee-background-position",
        defaultValue: "initial",
        label: "Background position",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      backgroundRepeat: {
        cssProperty: "background-repeat",
        cssVariableName: "--marquee-background-repeat",
        defaultValue: "initial",
        label: "Background repeat",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      backgroundBlendMode: {
        cssProperty: "background-blend-mode",
        cssVariableName: "--marquee-background-blend-mode",
        defaultValue: "initial",
        label: "Background blend mode",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      boxShadow: {
        cssProperty: "box-shadow",
        cssVariableName: "--marquee-box-shadow",
        defaultValue: "none",
        label: "Box shadow",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      opacity: {
        cssProperty: "opacity",
        cssVariableName: "--marquee-opacity",
        defaultValue: "1",
        label: "Opacity",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      backdropFilter: {
        cssProperty: "backdrop-filter",
        cssVariableName: "--marquee-backdrop-filter",
        defaultValue: "none",
        label: "Backdrop filter",
        role: "styling",
        roleGroup: "Surface",
        schemaType: "string",
        type: "text",
      },
      borderWidth: {
        cssProperty: "border-width",
        cssVariableName: "--marquee-border-width",
        defaultValue: "0px",
        label: "Border width",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      borderColor: {
        cssProperty: "border-color",
        cssVariableName: "--marquee-border-color",
        defaultValue: "transparent",
        label: "Border color",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "color",
      },
      borderRadius: {
        cssProperty: "border-radius",
        cssVariableName: "--marquee-border-radius",
        defaultValue: "0px",
        label: "Border radius",
        role: "styling",
        roleGroup: "Border",
        schemaType: "string",
        type: "text",
      },
      isVisible: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: true,
        label: "Is visible",
        role: "visibility",
        roleGroup: "Visibility",
        schemaType: "boolean",
        type: "switch",
      },
      selectors: {
        cssProperty: null,
        cssVariableName: null,
        defaultValue: [],
        label: "Selectors",
        role: "selectors",
        roleGroup: "Selectors",
        schemaType: "array",
        type: "selectors",
      },
    },
    slots: {
      body: {
        allowedChildComponents: ["Accordion", "Alert", "Badge", "Button", "Canvas", "Card", "Checkbox", "Dialog", "Divider", "Element", "Form", "Grid", "Heading", "Icon", "Image", "Input", "Label", "Link", "List", "Map", "Marquee", "MenuBar", "ProgressBar", "Rating", "RichText", "RadioGroup", "Section", "Select", "Spacer", "Spinner", "Switch", "TabPane", "Table", "Text", "TextArea"],
      },
    },
  };
}
